# 要在此项目中启用 Dependabot 版本更新，请取消注释以下内容

version: 2
updates:
  # 维护 Python 依赖项的版本更新
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # 指定要忽略的依赖项更新（可选）
    ignore:
      - dependency-name: "flask"
        # 对于 Flask，只允许补丁版本更新
        update-types: ["version-update:semver-patch"]
    
  # 启用 GitHub Actions 的版本更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"